import type { ActivityEvent, AgentSession, ApprovalRequest, Workflow } from "@/lib/types";

export const initialAgents: AgentSession[] = [
  {
    id: "auth-svc",
    name: "Auth service",
    objective: "Implement secure session refresh and role-aware route protection",
    repository: "MahirG/CodexSimulator",
    branch: "agent/auth-hardening",
    status: "thinking",
    progress: 68,
    elapsed: "12m 44s",
    filesChanged: 7,
    additions: 284,
    deletions: 61,
    lastEvent: "Reviewing middleware and session boundaries",
    unread: false,
    reasoning: "high",
  },
  {
    id: "deck-ui",
    name: "Command deck",
    objective: "Build responsive hardware-inspired agent controls",
    repository: "MahirG/CodexSimulator",
    branch: "agent/command-deck",
    status: "complete",
    progress: 100,
    elapsed: "8m 09s",
    filesChanged: 12,
    additions: 711,
    deletions: 118,
    lastEvent: "Responsive layout and keyboard controls completed",
    unread: true,
    reasoning: "medium",
  },
  {
    id: "db-schema",
    name: "Data model",
    objective: "Create workspace, agent, workflow, approval, and audit schema",
    repository: "MahirG/CodexSimulator",
    branch: "agent/supabase-schema",
    status: "requires_input",
    progress: 81,
    elapsed: "16m 22s",
    filesChanged: 3,
    additions: 436,
    deletions: 9,
    lastEvent: "Permission required before applying database migration",
    unread: true,
    reasoning: "max",
  },
  {
    id: "test-suite",
    name: "Test runner",
    objective: "Validate production build, accessibility, and critical interactions",
    repository: "MahirG/CodexSimulator",
    branch: "agent/quality-gates",
    status: "idle",
    progress: 22,
    elapsed: "3m 18s",
    filesChanged: 2,
    additions: 93,
    deletions: 12,
    lastEvent: "Waiting for application changes",
    unread: false,
    reasoning: "medium",
  },
  {
    id: "bridge",
    name: "Local bridge",
    objective: "Design authenticated local bridge protocol for Git and shell execution",
    repository: "MahirG/CodexSimulator",
    branch: "agent/local-bridge",
    status: "error",
    progress: 43,
    elapsed: "9m 51s",
    filesChanged: 5,
    additions: 176,
    deletions: 34,
    lastEvent: "Bridge handshake expired; retry required",
    unread: true,
    reasoning: "high",
  },
  {
    id: "docs",
    name: "Architecture docs",
    objective: "Document security model, event protocol, and implementation roadmap",
    repository: "MahirG/CodexSimulator",
    branch: "agent/docs",
    status: "idle",
    progress: 54,
    elapsed: "5m 26s",
    filesChanged: 4,
    additions: 321,
    deletions: 15,
    lastEvent: "Architecture overview drafted",
    unread: false,
    reasoning: "low",
  },
];

export const initialEvents: ActivityEvent[] = [
  { id: "evt-1", agentId: "auth-svc", type: "agent.thinking", message: "Auth service is reviewing session boundaries", timestamp: "09:41:12", severity: "neutral" },
  { id: "evt-2", agentId: "deck-ui", type: "agent.complete", message: "Command deck completed responsive layout", timestamp: "09:42:07", severity: "success" },
  { id: "evt-3", agentId: "db-schema", type: "agent.requires_input", message: "Data model requests migration approval", timestamp: "09:43:25", severity: "warning" },
  { id: "evt-4", agentId: "bridge", type: "agent.error", message: "Local bridge handshake expired", timestamp: "09:44:03", severity: "danger" },
];

export const approvalRequests: ApprovalRequest[] = [
  {
    id: "approval-schema",
    agentId: "db-schema",
    title: "Apply Supabase migration",
    detail: "Create the initial workspace, agent, workflow, approval, notification, and audit tables with row-level security enabled.",
    command: "supabase db push",
    scope: "Development Supabase project only",
    reversible: true,
    networkAccess: true,
    risk: "high",
    createdAt: "2 minutes ago",
  },
];

export const workflows: Workflow[] = [
  {
    id: "review-pr",
    name: "Review pull request",
    description: "Inspect a diff, run quality checks, summarize risk, and request approval before submitting a review.",
    trigger: "Manual",
    runs: 38,
    successRate: 94,
    steps: [
      { id: "review-1", label: "Read PR context", type: "agent", state: "complete" },
      { id: "review-2", label: "Inspect changed files", type: "git", state: "complete" },
      { id: "review-3", label: "Run quality checks", type: "test", state: "running" },
      { id: "review-4", label: "Approve review", type: "approval", state: "queued" },
    ],
  },
  {
    id: "safe-feature",
    name: "Build feature safely",
    description: "Create an isolated branch, implement a scoped feature, validate it, and open a draft pull request.",
    trigger: "New task",
    runs: 17,
    successRate: 88,
    steps: [
      { id: "feature-1", label: "Create worktree", type: "git", state: "complete" },
      { id: "feature-2", label: "Implement task", type: "agent", state: "running" },
      { id: "feature-3", label: "Run build and tests", type: "test", state: "queued" },
      { id: "feature-4", label: "Open draft PR", type: "git", state: "queued" },
    ],
  },
  {
    id: "incident",
    name: "Investigate incident",
    description: "Collect logs, identify the likely regression, prepare a reversible fix, and stop before production deployment.",
    trigger: "Alert",
    runs: 9,
    successRate: 100,
    steps: [
      { id: "incident-1", label: "Collect runtime evidence", type: "agent", state: "complete" },
      { id: "incident-2", label: "Bisect regression", type: "git", state: "running" },
      { id: "incident-3", label: "Prepare patch", type: "agent", state: "queued" },
      { id: "incident-4", label: "Production approval", type: "approval", state: "blocked" },
    ],
  },
];
